const List<String> categories = [
  'Family & Friends',
  'Work',
  'Health',
  'Wealth',
  'Interests'
];

const Map<String, String> categoryIconAsset = {
  'Family & Friends' : 'images/cat1.png',
  'Work' : 'images/cat2.png',
  'Health' : 'images/cat3.png',
  'Wealth' : 'images/cat4.png',
  'Interests' : 'images/cat5.png',
};

const Map<String, String> categoryImageAsset = {
  'Family & Friends' : 'images/banner1.png',
  'Work' : 'images/banner2.png',
  'Health' : 'images/banner3.png',
  'Wealth' : 'images/banner4.png',
  'Interests' : 'images/banner5.png',
};

const Map<String, List<String>> questTitles1 = {
  'Family & Friends': [
    'Make a plan for buying a house',
    'Upgrade the security system of our home',
    'Celebrate someone\'s birthday',
    'Find a good teacher for the kids',
    'Host a party this weekend ',
  ],
  'Work': [
    'Get promotion by the end of this year',
    'Accomplish the project goals before the deadline',
    'Be a good mentor',
    'Learn new professional skills',
    'Buy yourself a better car/motor',
  ],
  'Health': [
    'Charge mechanical parts 8 hours per day',
    'Join a body training club',
    'Make a body part maintenance plan',
  ],
  'Wealth': [
    'Save money for a more substantial body part',
    'Get an insurance plan',
    'Start to track your spending',
  ],
  'Interests': [
    'Travel to a planet',
    'Cook dinner once a week',
    'Get a plant and take care of it',
    'Join a club',
    'Watch movies that you always want to watch',
  ]
};

const Map<String, double> avgLife = {
  'Hong Kong': 84.7,
  'Japan': 84.5,
  'Singapore': 83.8,
  'Italy': 83.6,
  'Spain': 83.4,
  'Switzerland': 83.4,
  'Australia': 83.3,
  'Iceland': 82.9,
  'Israel': 82.8,
  'South Korea': 82.8,
  'Sweden': 82.7,
  'France': 82,
  'Malta': 82.4,
  'Canada': 82.3,
  'Norway': 82.3,
  'Greece': 82.1,
  'Ireland': 82.1,
  'Luxembourg': 82.1,
  'Netherlands': 82.1,
  'New Zealand': 82.1,
  'Portugal': 81.9,
  'Andorra': 81.8,
  'Finland': 81.7,
  'Belgium': 81.5,
  'Austria': 81.4,
  'Germany': 81.2,
  'Slovenia': 81.2,
  'United Kingdom': 81.2,
  'European Union': 81.2,
  'Cyprus': 80.8,
  'Denmark': 80.8,
  'Liechtenstein': 80.5,
  'Taiwan': 80.4,
  'Costa Rica': 80.1,
  'Chile': 80.0,
  'Czech Republic': 79.2,
  'Barbados': 79.1,
  'Lebanon': 78.9,
  'United States': 78.9,
  'Cuba': 78.6,
  'Estonia': 78.6,
  'Poland': 78.5,
  'Croatia': 78.3,
  'Panama': 78.3,
  'Turkey': 78.3,
  'United Arb Emirates': 77.8,
  'Uruguay': 77.8,
  'Oman': 77.6,
  'Slovakia': 77.4,
  'Bosnia and Herzegovina': 77.3,
  'Bahrain': 77.2,
  'Colombia': 77.1,
  'Antigua and Varbuda': 76.9,
  'Thailand': 76.9,
  'Ecuador': 76.8,
  'Montenegro': 76.8,
  'Sri Lanka': 76.8,
  'Algeria': 76.7,
  'Hungary': 76.7,
  "China": 76.7,
  'Argentina': 76.5,
  'Iran': 76.5,
  'Morocco': 76.5,
  'Peru': 76.5,
  'Tunisia': 76.5,
  'Malaysia': 76.1,
  'Saint Lucia': 76.1,
  'Romania': 75.9,
  'Serbia': 75.8,
  'Brazil': 75.1,
  'Brunei': 75.7,
  'Lithuania': 75.7,
  'North Macedonia': 75.7,
  'Kuwait': 75.4,
  'Latin America And Caribbean': 75.4,
  'East Asia, Southeast Asia and Oceania': 75.3,
  'Vietnam': 75.3,
  'Latvia': 75.2,
  'Honduras': 75.1,
  'Mexico': 75.0,
  'Saudi Arabia': 75.0,
  'Armenia': 74.9,
  'Bulgaria': 74.9,
  'Mauritius': 74.9,
  'Belarus': 74.6,
  'Saint Kits and Nevis': 74.6,
  'Belize': 74.5,
  'Jamaica': 74.4,
  'Jordan': 74.4,
  'Nicaragua': 74.3,
  'Guatemala': 74.1,
  'Paraguay': 74.1,
  'Dominican Republic': 73.9,
  'Marshall Islands': 73.9,
  'Palestine': 73.9,
  'Bahamas': 73.8,
  'Palau': 73.7,
};
