const List<String> categories = [
  'Environment',
  'Family',
  'Work',
  'Entertainment',
  'Health',
  'Self-growth'
];

const List<String> questTitles = [
  'Clean Beach',
  'Reading a Book',
  'Wash My Cat',
  'Propose',
  'Raise a Child',
  'Aurora',
  'Write an App',
  'Reduce Waste',
  'Fitness',
  'Lose Weight',
  'Housework',
  'Visiting Grandparents',
  'Live in a Woods',
  'Parachute',
  'Rock Climbing',
  'Learning Cooking'
];

const Map<String, List<String>> questTitles1 = {
  'Environment': [
    'Clean Beach',
    'Reduce Waste',
    'Global Warming',
    'Planting Trees',
  ],
  'Family': [
    'Wash My Cat',
    'Propose',
    'Raise a Child',
    'Housework',
    'Visiting Grandparents',
  ],
  'Work': [
    'Write an App',
    'Presentation Skill',
    'Communication Skill',
    'Financial Knowledge',
  ],
  'Entertainment': [
    'Aurora',
    'Live in a Woods',
    'Parachute',
    'Rock Climbing',
  ],
  'Health': [
    'Fitness',
    'Lose Weight',
  ],
  'Self-growth': [
    'Reading a Book',
    'Learn a Skill',
    'Learn Cooking',
    'Photography',
  ],
};

const Map<String, double> avgLife = {
  'Hong Kong': 84.7,
  'Japan': 84.5,
  'Singapore': 83.8,
  'Italy': 83.6,
  'Spain': 83.4,
  'Switzerland': 83.4,
  'Australia': 83.3,
  'Iceland': 82.9,
  'Israel': 82.8,
  'South Korea': 82.8,
  'Sweden': 82.7,
  'France': 82,
  'Malta': 82.4,
  'Canada': 82.3,
  'Norway': 82.3,
  'Greece': 82.1,
  'Ireland': 82.1,
  'Luxembourg': 82.1,
  'Netherlands': 82.1,
  'New Zealand': 82.1,
  'Portugal': 81.9,
  'Andorra': 81.8,
  'Finland': 81.7,
  'Belgium': 81.5,
  'Austria': 81.4,
  'Germany': 81.2,
  'Slovenia': 81.2,
  'United Kingdom': 81.2,
  'European Union': 81.2,
  'Cyprus': 80.8,
  'Denmark': 80.8,
  'Liechtenstein': 80.5,
  'Taiwan': 80.4,
  'Costa Rica': 80.1,
  'Chile': 80.0,
  'Czech Republic': 79.2,
  'Barbados': 79.1,
  'Lebanon': 78.9,
  'United States': 78.9,
  'Cuba': 78.6,
  'Estonia': 78.6,
  'Poland': 78.5,
  'Croatia': 78.3,
  'Panama': 78.3,
  'Turkey': 78.3,
  'United Arb Emirates': 77.8,
  'Uruguay': 77.8,
  'Oman': 77.6,
  'Slovakia': 77.4,
  'Bosnia and Herzegovina': 77.3,
  'Bahrain': 77.2,
  'Colombia': 77.1,
  'Antigua and Varbuda': 76.9,
  'Thailand': 76.9,
  'Ecuador': 76.8,
  'Montenegro': 76.8,
  'Sri Lanka': 76.8,
  'Algeria': 76.7,
  'Hungary': 76.7,
  "China": 76.7,
  'Argentina': 76.5,
  'Iran': 76.5,
  'Morocco': 76.5,
  'Peru': 76.5,
  'Tunisia': 76.5,
  'Malaysia': 76.1,
  'Saint Lucia': 76.1,
  'Romania': 75.9,
  'Serbia': 75.8,
  'Brazil': 75.1,
  'Brunei': 75.7,
  'Lithuania': 75.7,
  'North Macedonia': 75.7,
  'Kuwait': 75.4,
  'Latin America And Caribbean': 75.4,
  'East Asia, Southeast Asia and Oceania': 75.3,
  'Vietnam': 75.3,
  'Latvia': 75.2,
  'Honduras': 75.1,
  'Mexico': 75.0,
  'Saudi Arabia': 75.0,
  'Armenia': 74.9,
  'Bulgaria': 74.9,
  'Mauritius': 74.9,
  'Belarus': 74.6,
  'Saint Kits and Nevis': 74.6,
  'Belize': 74.5,
  'Jamaica': 74.4,
  'Jordan': 74.4,
  'Nicaragua': 74.3,
  'Guatemala': 74.1,
  'Paraguay': 74.1,
  'Dominican Republic': 73.9,
  'Marshall Islands': 73.9,
  'Palestine': 73.9,
  'Bahamas': 73.8,
  'Palau': 73.7,
};
